@startuml
class Agente {
  - nombre: String
  - salud: int
  - arma: String
  + disparar(): void
  + usarHabilidad(): void
  + recargar(): void
  + comunicar(): void
}

class AgenteDefensivo {
  - habilidadDefensiva: String
  + curar(): void
}

class AgenteOfensivo {
  - habilidadOfensiva: String
  + lanzarGranada(): void
}

class AgenteSoporte {
  - habilidadSoporte: String
  + otorgarEscudo(): void
}

class Habilidad {
  - nombreHabilidad: String
  - costo: int
  + activar(): void
}

class Equipo {
  - nombre: String
  + coordinarAtaque(): void
}

Agente <|-- AgenteDefensivo : hereda
Agente <|-- AgenteOfensivo : hereda
Agente <|-- AgenteSoporte : hereda

AgenteOfensivo "1" *-- "0..*" Habilidad : usa
AgenteDefensivo "1" *-- "0..*" Habilidad : usa
AgenteSoporte    "1" *-- "0..*" Habilidad : usa

Equipo "1" *-- "1..5" Agente : contiene >

@enduml
